### ISSUE TITLE
Please, how to execute the wireguard.js script correctly?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [vchrizz/ER-wizard-WireGuard#30]
Please, how to execute the wireguard.js script correctly?  I have node installed, but the script does not execute?

```
# node -v
v18.19.1

# node wireguard.js
/root/wireguard.js:174
        window.wireguard = {
        ^

ReferenceError: window is not defined
    at /root/wireguard.js:174:2
    at Object.<anonymous> (/root/wireguard.js:184:3)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49

Node.js v18.19.1
```

**Comment by vchrizz** [comment]
sorry, the wizard does not ship any .js file?
its just

- wizard.html (GUI part)
- wizard-run (backend / shell-script)
- validator.json (required for EdgeOS)

The wizard is not meant to be used with node.
You upload it to the EdgeOS router, like described here:
https://github.com/vchrizz/ER-wizard-WireGuard?tab=readme-ov-file#installation

I am not sure, what you want to do and which wireguard.js file you are talking about, maybe you are asking here in the wrong place?
